fix: fix issues and add team change
masastack/MASA.DCC pull request #208
Opened 2022-09-16 09:36 UTC by codding-y

2022-09-16 10:01 UTC, doddgu requested changes

2022-09-16 10:01 UTC, doddgu commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Rcl/Pages/Label.razor.cs
> +                    await PopupService.ToastErrorAsync("标签Code和标签Name不允许重复");
I18n

2022-09-16 10:35 UTC, codding-y commented on src/Services/Masa.Dcc.Service/Infrastructure/Repositories/App/AppPinRepository.cs
> +                .Select(app => app.OrderByDescending(a => a.Id).First())
Wow!!!  Indeed.

2022-09-19 01:09 UTC, doddgu approved these changes
LGTM

2022-09-19 01:09 UTC, merged