Keys separated by English dot get last, configure the English languag…
masastack/MASA.DCC pull request #346
Opened 2023-02-25 08:59 UTC by zyz

…e package

# Description

_Only configure the English languag_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-02-26 02:48 UTC, doddgu requested changes

2023-02-26 02:48 UTC, doddgu commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Rcl/wwwroot/i18n/en-US.json
> +    "The configuration object name conflicts, and the same configuration object name will overwrite the configuration information. If you need to clone, please modify the configuration object name":
The key is too long. This is not a best practice.

2023-02-26 02:49 UTC, doddgu commented
@codding-y PTAL

2023-03-10 03:26 UTC, codding-y approved these changes

2023-03-10 03:31 UTC, codding-y approved these changes
LGTM

2023-03-10 04:37 UTC, merged