public configuration, only other clisters of the currently configured…
masastack/MASA.DCC pull request #373
Opened 2023-03-03 13:22 UTC by zyz

… object are cloned, remove step bar

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-03-07 06:16 UTC, doddgu commented
@codding-y PTAL

2023-03-08 06:31 UTC, codding-y requested changes

2023-03-08 06:31 UTC, codding-y commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Rcl/Pages/Modal/CloneModal.razor
> +										</MRow>
Code format

2023-03-08 06:36 UTC, codding-y approved these changes

2023-03-08 06:37 UTC, merged