feat:update clonemodal and releeasehistorymodal css
masastack/MASA.DCC pull request #385
Opened 2023-03-07 08:42 UTC by kogel-net

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-03-07 10:35 UTC, doddgu commented
@codding-y PTAL

2023-03-08 02:49 UTC, codding-y commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Rcl/Pages/Modal/CloneModal.razor
> +                                                                          Outlined
remove black space

2023-03-08 03:05 UTC, codding-y requested changes
Razor code format

2023-03-08 03:05 UTC, codding-y commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Rcl/Pages/Modal/CloneModal.razor.css
> +    background-color: red;
red?

2023-03-08 03:05 UTC, codding-y commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Rcl/Pages/Modal/CloneModal.razor.css
> +        background-color: red;
The design is red？

2023-03-10 03:36 UTC, codding-y approved these changes

2023-03-10 03:37 UTC, codding-y approved these changes
LGTM

2023-03-10 04:37 UTC, doddgu commented
@kogel-net resolve conflict

2023-03-10 05:51 UTC, merged