feat:Solve the problem of label type code duplication
masastack/MASA.DCC pull request #416
Opened 2023-03-13 06:59 UTC by kogel-net

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-03-13 08:15 UTC, MayueCif commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Rcl/Pages/Label.razor.cs
> +                    if (labels.Any())
这部分逻辑应该放在service

2023-03-13 08:16 UTC, MayueCif reviewed
@kogel-net

2023-03-15 05:39 UTC, codding-y requested changes

2023-03-15 05:39 UTC, codding-y commented on src/Services/Masa.Dcc.Service/Domain/Label/Services/LabelDomainService.cs
> +using Masa.BuildingBlocks.Globalization.I18n;
Move to global using

2023-03-15 05:39 UTC, codding-y commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Server/Program.cs
> +    );
Logical repetition

2023-03-15 05:48 UTC, codding-y requested changes

2023-03-15 05:48 UTC, codding-y commented on .gitignore
> +/src/Services/Masa.Dcc.Service/Assets/Fonts/SourceHanSansCN-Normal.ttf
Don't put font files in the project. Can use CDN.

2023-03-17 09:05 UTC, codding-y requested changes

2023-03-17 09:05 UTC, codding-y commented on src/Web/Masa.Dcc.Web.Admin/Masa.Dcc.Web.Admin.Server/Program.cs
> +builder.Services.AddDccApiGateways(c => c.DccServiceAddress = masaStackConfig.GetDccServiceDomain());
builder.Services.AddDccApiGateways(c =>	
#if DEBUG	
    c.DccServiceAddress = "http://localhost:6196"	
#else	
    c.DccServiceAddress = masaStackConfig.GetDccServiceDomain()	
#endif	
    );

2023-03-20 05:24 UTC, MayueCif approved these changes

2023-03-20 05:30 UTC, codding-y requested changes

2023-03-20 05:30 UTC, codding-y commented on src/Services/Masa.Dcc.Service/Masa.Dcc.Service.Admin.csproj
> +	  <Folder Include="Assets\Fonts\" />
Why Fonts are needed？

2023-03-20 05:37 UTC, codding-y approved these changes

2023-03-20 05:37 UTC, merged